# version: "3.9" 

services:
  fastapi:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:${FASTAPI_PORT}:${FASTAPI_PORT}"
    env_file:
      - .env
    depends_on:
      - postgres
    command: ["bash", "-c", "uv run fastapi dev --host 0.0.0.0"]
    
    

  postgres:
    image: postgres:18.1
    container_name: postgres
    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4.2.0
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "${RABBITMQ_AMQP_PORT}:${RABBITMQ_AMQP_PORT}"
      - "${RABBITMQ_WEB_PORT}:${RABBITMQ_WEB_PORT}"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
  
  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
    driver: local
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local
  redis_data:
    driver: local
  

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."
